Github.Client.get_user_repos("teamon")
Github.Client.get_user_repos("danilo-vieira")
Github.Client.get_user_repos("librity")
Github.Client.get_user_repos(" ")
Github.Client.get_user_repos("")

[head | tails] = Github.Client.get_user_repos("librity")
head |> IO.inspect(limit: :infinity)

# %{
#   "statuses_url" => "https://api.github.com/repos/librity/aircnc_full_stack/statuses/{sha}",
#   "git_refs_url" => "https://api.github.com/repos/librity/aircnc_full_stack/git/refs{/sha}",
#   "issue_comment_url" => "https://api.github.com/repos/librity/aircnc_full_stack/issues/comments{/number}",
#   "watchers" => 0,
#   "disabled" => false,
#   "mirror_url" => nil,
#   "languages_url" => "https://api.github.com/repos/librity/aircnc_full_stack/languages",
#   "stargazers_count" => 0,
#   "license" => nil,
#   "forks" => 0,
#   "default_branch" => "master",
#   "comments_url" => "https://api.github.com/repos/librity/aircnc_full_stack/comments{/number}",
#   "commits_url" => "https://api.github.com/repos/librity/aircnc_full_stack/commits{/sha}",
#   "id" => 213098242,
#   "clone_url" => "https://github.com/librity/aircnc_full_stack.git",
#   "homepage" => "https://rocketseat.com.br/week-9/aulas",
#   "stargazers_url" => "https://api.github.com/repos/librity/aircnc_full_stack/stargazers",
#   "events_url" => "https://api.github.com/repos/librity/aircnc_full_stack/events",
#   "blobs_url" => "https://api.github.com/repos/librity/aircnc_full_stack/git/blobs{/sha}",
#   "forks_count" => 0,
#   "pushed_at" => "2021-03-31T03:20:12Z",
#   "git_url" => "git://github.com/librity/aircnc_full_stack.git",
#   "hooks_url" => "https://api.github.com/repos/librity/aircnc_full_stack/hooks",
#   "owner" => %{
#     "avatar_url" => "https://avatars.githubusercontent.com/u/19496542?v=4",
#     "events_url" => "https://api.github.com/users/librity/events{/privacy}",
#     "followers_url" => "https://api.github.com/users/librity/followers",
#     "following_url" => "https://api.github.com/users/librity/following{/other_user}",
#     "gists_url" => "https://api.github.com/users/librity/gists{/gist_id}",
#     "gravatar_id" => "",
#     "html_url" => "https://github.com/librity",
#     "id" => 19496542,
#     "login" => "librity",
#     "node_id" => "MDQ6VXNlcjE5NDk2NTQy",
#     "organizations_url" => "https://api.github.com/users/librity/orgs",
#     "received_events_url" => "https://api.github.com/users/librity/received_events",
#     "repos_url" => "https://api.github.com/users/librity/repos",
#     "site_admin" => false,
#     "starred_url" => "https://api.github.com/users/librity/starred{/owner}{/repo}",
#     "subscriptions_url" => "https://api.github.com/users/librity/subscriptions",
#     "type" => "User",
#     "url" => "https://api.github.com/users/librity"
#   },
#   "trees_url" => "https://api.github.com/repos/librity/aircnc_full_stack/git/trees{/sha}",
#   "git_commits_url" => "https://api.github.com/repos/librity/aircnc_full_stack/git/commits{/sha}",
#   "collaborators_url" => "https://api.github.com/repos/librity/aircnc_full_stack/collaborators{/collaborator}",
#   "watchers_count" => 0,
#   "archived" => false,
#   "tags_url" => "https://api.github.com/repos/librity/aircnc_full_stack/tags",
#   "merges_url" => "https://api.github.com/repos/librity/aircnc_full_stack/merges",
#   "releases_url" => "https://api.github.com/repos/librity/aircnc_full_stack/releases{/id}",
#   "subscribers_url" => "https://api.github.com/repos/librity/aircnc_full_stack/subscribers",
#   "ssh_url" => "git@github.com:librity/aircnc_full_stack.git",
#   "created_at" => "2019-10-06T02:23:30Z",
#   "name" => "aircnc_full_stack",
#   "has_issues" => true,
#   "private" => false,
#   "git_tags_url" => "https://api.github.com/repos/librity/aircnc_full_stack/git/tags{/sha}",
#   "has_projects" => true,
#   "archive_url" => "https://api.github.com/repos/librity/aircnc_full_stack/{archive_format}{/ref}",
#   "has_wiki" => true,
#   "open_issues_count" => 13,
#   "milestones_url" => "https://api.github.com/repos/librity/aircnc_full_stack/milestones{/number}",
#   "forks_url" => "https://api.github.com/repos/librity/aircnc_full_stack/forks",
#   "url" => "https://api.github.com/repos/librity/aircnc_full_stack",
#   "downloads_url" => "https://api.github.com/repos/librity/aircnc_full_stack/downloads",
#   "open_issues" => 13,
#   "keys_url" => "https://api.github.com/repos/librity/aircnc_full_stack/keys{/key_id}",
#   "description" => "Rocket Seat - Omnistack Week 9 - Full stack web and mobile app that allows tech companies to host prospective programmers for a day.",
#   "contents_url" => "https://api.github.com/repos/librity/aircnc_full_stack/contents/{+path}",
#   "language" => "JavaScript",
#   "contributors_url" => "https://api.github.com/repos/librity/aircnc_full_stack/contributors",
#   "deployments_url" => "https://api.github.com/repos/librity/aircnc_full_stack/deployments",
#   "pulls_url" => "https://api.github.com/repos/librity/aircnc_full_stack/pulls{/number}",
#   "labels_url" => "https://api.github.com/repos/librity/aircnc_full_stack/labels{/name}",
#   "html_url" => "https://github.com/librity/aircnc_full_stack",
#   "svn_url" => "https://github.com/librity/aircnc_full_stack",
#   "issue_events_url" => "https://api.github.com/repos/librity/aircnc_full_stack/issues/events{/number}",
#   "notifications_url" => "https://api.github.com/repos/librity/aircnc_full_stack/notifications{?since,all,participating}",
#   "has_downloads" => true,
#   "node_id" => "MDEwOlJlcG9zaXRvcnkyMTMwOTgyNDI=",
#   "compare_url" => "https://api.github.com/repos/librity/aircnc_full_stack/compare/{base}...{head}",
#   "full_name" => "librity/aircnc_full_stack",
#   "subscription_url" => "https://api.github.com/repos/librity/aircnc_full_stack/subscription",
#   "assignees_url" => "https://api.github.com/repos/librity/aircnc_full_stack/assignees{/user}",
#   "issues_url" => "https://api.github.com/repos/librity/aircnc_full_stack/issues{/number}",
#   "size" => 14551,
#   "has_pages" => false,
#   "fork" => false,
#   "updated_at" => "2021-03-09T03:17:46Z",
#   "branches_url" => "https://api.github.com/repos/librity/aircnc_full_stack/branches{/branch}",
#   "teams_url" => "https://api.github.com/repos/librity/aircnc_full_stack/teams"
# }
